sudo: required

language: node_js
cache:
    npm: false
node_js:
- node
before_script:
- npm install -g grunt-cli npm
- npm install
env:
  global:
    secure: Ko3UAXQaw88V6grm3GiFMYrhJxNl4Ba697TWkKXGqL2wJDc9DcBPhAnYGQR7cwmN2pemRSHUGGFA9YzXid8KBEfokrb8v4i72ZY5nzAOCpQPptr3lBkiVNfeKCxl9gCUObYzCBD3uRoA3jP+iwKv7Tsocfb+x7Os2jXYgQJpv6sVCATQqhDkFBG7E+BcZBnP56kF9kJzCpSLaFHwb525z7bR1DnRX2QmwvQaAepW5KBvEn3Ts7TLeJBIOVZtvGoJi2oOR1HDWqczJQEljaqnxvwdZwVWdO/goE/c81MGGspcj96Byl2cxUed/MBw4EEk7lO3rg5UlOEgQK1gQib/QwyfWEVLTtW78vt17YrSvFk9h3YnSfpNs7zEM7oK83ah7EnWc2P7FXBnYRvmXYf/s1OuuZMJXYkhMPq1lYT0mXXBxDdKEhpDLwbyAmMqosR1YMZ52NlA9gjR7Cbjmxe6Q6f+pp8q/nm9JyKr1FT99G5awtZzrd6GCCUn9L2xjrpPukiJ4DXw29I5M09hbhMsjwgccs0Paj5r2RtL9MsAK8i6hGamK3/2Iyhc8MPvDZ4Fh6uociAfXPqkkTRiati4LqBP9Gw0kuIJH0RFTZAAIIifHF/eq+QI2HI3s46dKl9iBPAjYmfqqTgQrPe1v63SR7H+bRqpNPsTkltI44Vjqpg=
