sudo: required
dist: trusty
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- node
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- npm install grunt-cli -g
- npm install
- node_modules/protractor/bin/webdriver-manager update --gecko=false
env:
  global:
    secure: SEQrMx8QYiu5cOYcH0A4nOQ5GjAbiD8hSrVG7rQOekuPPkNqVGjabQ4gasMmoCpECSlGQBVbGXlBWvbkq3C+o3SoTVArOBFuLzl39vYJJJD0gePX/Lh1L63ytDXXPyhUIBcetEBij+bbald6ckP9ZzPNlUxbGJ9D2Nc+6FBOgilFivmYLsB+5Kg3ebGPsArrUeff8vedx57VJcgwc37s+npfhHXmxrjsxl1nuhItJjylUH7vIJgz/ZfErFfX5xSRzvpwPXtYK93GS2eCMC6DAce1JD22p4EHRFfy58UhrUDuLtL7TSoXr7cZkfmWFRmLW5In0rOujgHV4hosB5cWVSYbTfC8aVieE5VhfKvQMHuhjCkfe/P0n/GOcRaI8XTIcEJS9ikMK2Aadx5Ok/Cgzlag+XDK3tpNBirZ5DGDaF9EhItADRrjkU+I7KJnWy+WP/x7q/8UHugjcwvSUtjKoCa9DHaBP9bNQEcmtdWpTWh5XkPBFqPAXGRxJd10Iiiy4qLhqSB4B7mn4F/LCfuHHG8apsLyILaj9+TKWIATltwvRjtHWERsJLW8vfPvG3OTnK0x4TzmuB3FrrnQo6BPu2XBN6xIFWX9qxYeG5hQUBxXa6d3EFlQ61kWrxYfcp2l4NTnol4rOSBXU63gFm5l7JL6v+05i0sZduN0RzgZk0g=
