sudo: required
dist: trusty
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- node
before_install: npm install -g npm
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- npm install -g grunt-cli npm
- npm install
- node_modules/protractor/bin/webdriver-manager update --gecko=false
env:
  global:
    secure: NgF3ocGe8i4/qgfYxeMsyAeTi0a/l+Se3PhywlWeNNIvaZrP6w/sYkCz5zY1+RXxXdOBpBJIdKVZrYjsVllPj8oVF89qK5QvHy7+fPrb0ruKqxlsFZKCia4awzvnD8ese4RxdQwWl71J0KoGTrVmHKUL0iN9TKsai3y51YXbxRKCppBhHeBMtNOQq0OtuZekbulcNUDptmRczNvnGiasOkqFENE1gdnZ+WyxIMQePKPsFZZfIWdU52Q08GN94VDBxTcDYzeXjWaQxuVi+9Zt+P5e//kvrFUnAYhKwnCkfAH9eEhaPUex7At+dJiwo/ERx3iNSSylayOWheHW86mf5pZpTETf6vUqoqeLgWVP3s4o4/lK8jlEXQ+CH0E1H0w4Y98veV6M9PytxMWDGs95fdzVnGYqwmWjy5TYv8GIjI/FFQ83ZIVjQS0a9N/sc72nKSQ+uXqQploPuOrYPkrRA2mCHEIGhN+sjNxEKEQ+RSluMKXY5K9HkNE6MBHMSyXF15kbn6aDuzYaflrs1h/E803+/37F/EIhOq126bH/puBIpQIAuf5r1oIBDjryRNPL8ZIVAloBFKY+5TGm9ll7nkpCuuDzkP2gEeCYiTFfXmb1Z/0P+qC+nzxTBy0eVztwIm+iB8NS6gOz0HTBiLPuwiFY2DZ3Ye61lRea6b//OHE=
